interpreter = ["bash", "-euo", "pipefail", "-c"]

[[group]]
name = "lints"
depends = ["gen"]

[[group]]
name = "tests"
depends = ["gen"]

[[task]]
name = "protoc"
group = "gen"
script = "gen-proto"

[[task]]
name = "reuse"
group = "lints"
script = "reuse lint"

[[task]]
name = "markdownlint"
group = "lints"
script = """
git ls-files --cached --others --exclude-standard '*.md' | xargs markdownlint
"""

[[task]]
name = "gofmt"
group = "lints"
script = "test -z \"$(gofmt -l .)\""

[[task]]
name = "go-vet"
group = "lints"
script = "go vet ./..."

[[task]]
name = "shellcheck"
group = "lints"
script = "find bin -type f -exec shellcheck {} \\;"

[[task]]
name = "shfmt"
group = "lints"
script = "shfmt -d -i 4 ."

[[task]]
name = "go"
group = "tests"
script = "go test ./... -count=1"

[[task]]
name = "nix"
group = "build"
script = "nix build -f nix output.package.default"
